# Podfile

# Select the appropriate platform below
platform :ios
# platform :osx

#
# Some other entries might already exist in the file
# ...
#

# Add Kiwi as an exclusive dependency for the AmazingAppTests target
target :TestTDDTests, :exclusive => true do
   pod 'Kiwi'
   pod 'OCMock'
end

